version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - textpod_data:/app/data
      - ./backups:/app/backups
    environment:
      - LISTEN=0.0.0.0

volumes:
  textpod_data:
    name: textpod_data
